//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45TEAM7A
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.BookTransDetails = new HashSet<BookTransDetail>();
        }
    
        public int BookID { get; set; }
        public string BookTitle { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string BookCategory { get; set; }
        public string BookType { get; set; }
        public bool LoanStatus { get; set; }
        public string ISBN { get; set; }
        public string Edition { get; set; }
        public string Language { get; set; }
        public Nullable<System.DateTime> PublishedYear { get; set; }
    
        public virtual BkCategory BkCategory { get; set; }
        public virtual BookInventory BookInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookTransDetail> BookTransDetails { get; set; }
    }
}
