//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45TEAM7A
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTransDetail
    {
        public int TransactionID { get; set; }
        public int BookID { get; set; }
        public System.DateTime DateDue { get; set; }
        public Nullable<System.DateTime> DateReturn { get; set; }
        public bool RentalStatus { get; set; }
        public string Remarks { get; set; }
    
        public virtual book book { get; set; }
        public virtual BookTransaction BookTransaction { get; set; }
    }
}
