//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45TEAM7A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public short EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string TitleOfCourtesy { get; set; }
        public string EmployeePassword { get; set; }
    }
}
