//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45TEAM7A
{
    using System;
    using System.Collections.Generic;
    
    public partial class FineTran
    {
        public short MemberID { get; set; }
        public int TransactionID { get; set; }
        public decimal FineAmount { get; set; }
        public bool FineStatus { get; set; }
    
        public virtual BookTransaction BookTransaction { get; set; }
        public virtual BookTransaction BookTransaction1 { get; set; }
        public virtual Member Member { get; set; }
    }
}
