//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA45TEAM7A
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibrarySevenAEntities : DbContext
    {
        public LibrarySevenAEntities()
            : base("name=LibrarySevenAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BkCategory> BkCategories { get; set; }
        public virtual DbSet<BookInventory> BookInventories { get; set; }
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<BookTransaction> BookTransactions { get; set; }
        public virtual DbSet<BookTransDetail> BookTransDetails { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FineTran> FineTrans { get; set; }
        public virtual DbSet<Member> Members { get; set; }
    }
}
